name: CI Build Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4

      - name: Build CI
        run: |
          make arm_sdk_install
          make -j8
          tools/linux/xpack-arm-none-eabi-gcc-10.3.1-2.3/bin/arm-none-eabi-size obj/*.elf

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: AM32-bootloaders
          path: |
            obj/*.hex
          retention-days: 7
