name: CI Build MacOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build CI
        run: |
          make arm_sdk_install
          make -j8

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: AM32-bootloaders
          path: |
            obj/*.hex
          retention-days: 7
